language: php

php:
  - 7.1

branches:
  only:
    - master
    - development
    - /^feature\/.+$/
    - /^refactoring\/.+$/
    - /^issue\/.+$/

before_script:
 - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git checkout "$TRAVIS_BRANCH"; else git checkout -b "$TRAVIS_PULL_REQUEST_BRANCH"; fi
 - git reset --hard "$TRAVIS_COMMIT"
 - composer self-update
 - mkdir -p vendor/bin
 - mkdir -p build/logs
 - composer install -o --prefer-dist --no-interaction

script:
 - php vendor/bin/phpunit.phar -c build/

after_success:
 - travis_retry php vendor/bin/coveralls.phar -v --exclude-no-stmt
